### ISSUE TITLE
better error with multi-element GOPROXY

### ISSUE THREAD

**Issue by rogpeppe** [marwan-at-work/moddoc#8]
I ran moddoc with `GOPROXY=https://proxy.golang.org/,direct`, and I see errors like `Error while retrieving catalog from proxy: [unexpected status: 400]`.

Perhaps moddoc should fail fast when it sees a GOPROXY value like this.

**Comment by marwan-at-work** [comment]
@rogpeppe good point, for a quick fix moddoc can just split by `,` and take the first value. 

However, `moddoc` should also have the same behavior as the Go command by iterating through all proxies on `404` and `status-gone`

**Comment by marwan-at-work** [comment]
I'll push the quick fix now :)

**Comment by marwan-at-work** [comment]
@rogpeppe the quick fix is now in, I'll close this issue and open a new one for supporting multi proxy urls...though i really hope the Go team comes out with their own super solid server by that point lol. Thanks for chiming in here!
